//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateBase_10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staffs
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public int PostId { get; set; }
        public int TeacherId { get; set; }
        public int Rate { get; set; }
        public string Condition { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Posts Posts { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
